data:
  tokenizer_path: "./models/gpt-clean-16000.json"
  train_path: "./data/babylm_10M_clean"
  eval_path: "./data/babylm_dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "Llama" # or "GPT2"
  name: "Llama-16M"
  hidden_size: 256
  intermediate_size: 1024
  n_layer: 8
  n_head: 8 # Change this if you're using GPT2

training:
  lr: 3e-4
  batch_size: 128
  num_epochs: 4
  gradient_accumulation_steps: 1
  warmup_steps: 300
  fp16: True

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "./models/"

